### ISSUE TITLE
Crawl all stickers on the entire site?

### ISSUE THREAD

**Issue by chaoscreater** [appu1232/Line-Sticker-Mass-Dl#1]
Is it possible to download all stickers on the entire site in one go?

**Comment by appu1232** [comment]
Haven't looked much into how the site works and if there's a comprehensive list of all the sticker links somewhere, so I'm not sure. It's probably possible to develop this feature if if you can obtain said list, although this was kind of a one night project that I haven't really looked at since nor did I plan to expand upon.
